apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jaeger
  namespace: observability
spec:
  hosts:
    - jaeger.${DOMAIN}
  gateways:
    - istio-ingress/gateway
  http:
    - route:
        - destination:
            host: jaeger-query
            port:
              number: 16686
