apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: ${TRACING_SAMPLE_RATE}
        zipkin:
          address: jaeger-collector.observability:9411
